### ISSUE TITLE
  mntr <cmd> <args> ... seems not work

### ISSUE THREAD

**Issue by wulj2** [slw287r/mntr#1]
a execute my program with its arguments by mntr, I can see mntr generate the log file and start my program, however, after generate the log file, mntr itself aborted without any error? Is there anything wrong?

**Comment by slw287r** [comment]
Thank you for choosing `mntr`! Please provide more details for me to track down the problem:

* Is your program running to fast and just last for a few seconds?
* Would you please run your `cmd <args>` and the monitor it by process ID? `mntr <pid>`

**Comment by wulj2** [comment]
my command is ```mntr bwa mem -o aln.sam ~/database/hg38/hg38.fa t1.gz t2.gz``` 

t1.gz and t2.gz is about 60GB in size

after execute this command, it generate file ```17297.log```

i use command ```ps aux | grep mntr``` and ```top``` , but found not ```mntr``` process, however, my ```bwa mem...``` program is still running there
